#
# Module manifest for module 'ESETConnect'
#
# Generated by: Mitchell Wesdijk
#
# Generated on: 3/25/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'ESETConnect.psm1'

# Version number of this module.
ModuleVersion = '0.2'

# ID used to uniquely identify this module
GUID = 'c80ddff5-8c26-4c7f-8cac-6a07fcfc086f'

# Author of this module
Author = 'Mitchell Wesdijk'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) Mitchell Wesdijk. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell Module for ESET Connect'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.5.0'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport =  @('Get-ESETAuthToken', 'Get-ESETDevice', 'Move-ESETDevice', 'Rename-ESETDevice', 'Get-ESETDevicesBatch', 'Get-ESETDeviceGroups', 'Get-ESETDevicesInGroup')

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = ''

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('ESET')

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/m11tch/esetconnect_psm'


    } # End of PSData hashtable

} # End of PrivateData hashtable

}

